### PR TITLE
Support digest auth for security, newer and oem cameras that require strict ISAPI, better logging.

### PR DESCRIPTION
**Pull request by gjbadros**
Work with newer hikvision cameras, including those OEM'd to Hawk Eye surveillance sold through Amazon, by supporting stricter ISAPI URLs and ignoring XML namespace; slightly improved logging, too, to keep many related messages together in a single output so they are not interleaved in home assistant output.  Support Digest authentication, and make it the default.

### CODE REVIEW

**Comment by gjbadros** [comment]
@fbradyirl what do you think?  The travis CI check failure is not something new I introduced, but I'm happy to fix flake8 warnings as a separate commit after we get this easier-to-grok change done. (I don't want to mix stylistic changes with the functional improvement I'm proposing.)

Thanks

**Comment by fbradyirl** [comment]
Sounds good. Yes if you could fix any issues that would be great as I no longer use this plugin myself so I would ask you to support it if there’s any issues if possible. Thanks.

**Comment by gjbadros** [comment]
Cool, thanks, yea, I can try to help folks with it.  Will you be able to
make a release on pypi with this new version?  Or do you want me to either
take over that or make up a new name for this dependence?  I prefer you
just make the release and then I'll submit the PR for homeassistant, too,
since I don't anticipate making further enhancements -- I just needed these
changes for current hikvision oem cams.

Thx

**Comment by fbradyirl** [comment]
I can make a new release yep no problem. Just need to remember to do that. 👍

**Comment by gjbadros** [comment]
Cool, l'll keep a look out for it... Thanks!

**Pull request merged**
